### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by tswalker** [unoplatform/Uno.SQLitePCLRaw.Wasm#20]
i've tried loading this sample in both Chrome and Firefox.. issues in both:

Chrome: Version 66.0.3359.181
FireFox: 88.0 (64bit)

details from Chrome:
Failed to load resource: the server responded with a status of 404 ()
/package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/managed/System.Reflection.Emit.ILGeneration.clr:1 Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR
dotnet.js:8465 Uncaught (in promise) TypeError: Cannot read property 'ok' of undefined
    at handleFetchResponse (dotnet.js:8465)
/package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/managed/System.Reflection.Emit.Lightweight.clr:1 Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR

details from Firefox:
Loading failed for the <script> with source “https://sqliteefcore-wasm.platform.uno/package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/GoogleAnalytics.js”. sqliteefcore-wasm.platform.uno:1:1
Uncaught Error: Script error for "package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/GoogleAnalytics"
https://requirejs.org/docs/errors.html#scripterror
    makeError https://sqliteefcore-wasm.platform.uno/package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/require.js:5
    onScriptError https://sqliteefcore-wasm.platform.uno/package_67f26d099b775af17ff6f44ba4ed9d1c20ef97a8/require.js:5

**Comment by jeromelaban** [comment]
Thanks for the report. Would you be behind a firewall, or having an antivirus running ?

**Comment by tswalker** [comment]
my apologizes for the response delay.. not sure why i'm not getting notifications.

*yes* I am definitely behind a firewall, no proxy or transparent proxy caching.

**Comment by jeromelaban** [comment]
This kind of error is not something uno has control over. Are you able to use this app without issues: https://calculator.platform.uno/ ?

Or is it specific to using https://sqliteefcore-wasm.platform.uno ?

<blockquote><div><strong><a href="https://calculator.platform.uno/">Uno Calculator</a></strong></div><div>The Uno Calculator, a WebAssembly application developed with the Uno Platform, also available for iOS and Android.</div></blockquote>
<blockquote></blockquote>
