### ISSUE TITLE
Can't make EFCoreSample.Wasm project work on Visual Studio 2019 Preview 3

### ISSUE THREAD

**Issue by salaros** [unoplatform/Uno.SQLitePCLRaw.Wasm#4]
First of all thanks for creating such a great project as Uno.

I'm struggling at building your WASM version of EFCore sample. I think that the content of this repo might be outdated and / or subjected to bit decay, since Mono WASM is being actively developed. I'm currently stuck a the point when a specific version of WASM SDK is extracted to %temp% folder, but its layout doesn't match the one hard-coded (???) into MSBuild .target files.

I'm still figuring out how things work in Uno, so fixing its complex build system is far beyond my current Uno skills (:smile:)

**Comment by jeromelaban** [comment]
Thanks for trying out Uno!

For VS2019, updating to Uno.UI  and Uno.Wasm.Bootstrap packages to the latest dev should be enough to work. The latest bootstrap contains a fairly recent version of mono-wasm. Let us know which error you're getting with the latest bits.

We've made great progress in Uno lately, and we'll be updating this repo as well with the latest.

**Comment by salaros** [comment]
Yeah, I forgot to tell you that I've already updated to the latest preview versions of Uno.* dependencies.

```
error : System.IO.DirectoryNotFoundException: 
 Could not find a part of the path 
  'C:\Users\Salaros\AppData\Local\Temp\mono-wasm-817b4795403\wasm-bcl\wasm'.
```

![image](https://user-images.githubusercontent.com/675348/53108336-e73d1180-3547-11e9-971b-17e0c492a9a9.png)

Please take a look [at my fork](https://github.com/salaros/Uno.SQLitePCLRaw.Wasm/) and try to reproduce the problem I'm currently struggling with.

**Comment by jeromelaban** [comment]
This error is generally caused by an invalid temporary mono-wasm folder, try deleting manually and rebuild

**Comment by salaros** [comment]
I've already tried it, the folder is recreated with the same content, which also 100% identical to the content of `mono-wasm-817b4795403.zip` downloaded by MSBuild.
I think that the the content of `mono-wasm-817b4795403.zip` is somehow different from what Uno.Wasm.Bootstrap expects it to be.

BTW I forgot to push [this commit](https://github.com/salaros/Uno.SQLitePCLRaw.Wasm/commit/83e213eceebe8419fad4e1c61e86a8f0a3dcc087), the commit I was talking about above

**Comment by jeromelaban** [comment]
Found the reason, there's an override of the mono sdk, just [drop this line](https://github.com/salaros/Uno.SQLitePCLRaw.Wasm/blob/83e213eceebe8419fad4e1c61e86a8f0a3dcc087/src/samples/EFCoreSample/EFCoreSample.Wasm/EFCoreSample.Wasm.csproj#L9) it was an override to make parts of roslyn work.

That being said, with recent version of mono-wasm, Roslyn needs to be configured differently (the assemblies are not readily available as they previously were) so you can use the [UWP head "static" compilation mode](https://github.com/salaros/Uno.SQLitePCLRaw.Wasm/blob/83e213eceebe8419fad4e1c61e86a8f0a3dcc087/src/samples/EFCoreSample/EFCoreSample.Shared/MainPage.xaml.cs#L40) in the mean time.

**Comment by salaros** [comment]
OK, seems like now a correct version of Mono Wasm SDK is downloaded, but I'm still getting problems

![image](https://user-images.githubusercontent.com/675348/53190000-c7761e00-3619-11e9-99e4-e028555331d2.png)

![image](https://user-images.githubusercontent.com/675348/53190525-da3d2280-361a-11e9-8ec9-8013c5990bbf.png)

I will try to compile it using WSL and then on real Ubuntu later. However it would be great to have a compiled version (for Windows, Linux or both) in GitHub Releases, so people could try it.

Could you provide a compiled version in Releases, because the compilation process seems to be tricky and it's OK, because the underlying technologies are bleeding edge etc

P.S. It would be great to have a NuGet package of SQLite implementation ready to use with Uno, Blazor etc

**Comment by jeromelaban** [comment]
For the first error, this is caused by the linker, you can see the error message when setting your build output in detailed or diagnostics.

For the second, you need to add this: 
`<DotNetCliToolReference Include="Uno.Wasm.Bootstrap.Cli" Version="1.0.0-dev.1" />`
See : https://github.com/nventive/Uno.Wasm.Bootstrap#how-to-use-the-package. Just make sure to adjust the version number to the latest package available.

**Comment by salaros** [comment]
So for some reason, even if there is a reference to `Microsoft.CodeAnalysis` (I've tried adding sub-dependencies as project dependencies, below you will see why I did it)

![image](https://user-images.githubusercontent.com/675348/53194575-bbdc2480-3624-11e9-89cb-48eda9acda07.png)

and entries in `LinkerConfig.xml` file

![image](https://user-images.githubusercontent.com/675348/53194669-f6de5800-3624-11e9-9c42-162fcd82e355.png)

![image](https://user-images.githubusercontent.com/675348/53194603-ca2a4080-3624-11e9-9d7d-eaf32c264894.png)

Mono.Linker still cannot find `Microsoft.CodeAnalysis.CSharp.Workspaces` dependency for some reason. Probably using Visual Studio and Windows is a bad idea.

```
    Fatal error in Mono CIL Linker
    Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: resource EFCoreSample.Wasm.xml in EFCoreSample.Wasm, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.CodeAnalysis.CSharp.Workspaces, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
       at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
       at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
       at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
       --- End of inner exception stack trace ---
       at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
       at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator)
       at Mono.Linker.Steps.ResolveFromXmlStep.Process()
       --- End of inner exception stack trace ---
       at Mono.Linker.Steps.ResolveFromXmlStep.Process()
       at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
       at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
       at Mono.Linker.Pipeline.Process(LinkContext context)
       at Mono.Linker.Driver.Run(ILogger customLogger)
       at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
    C:\Users\Salaros\.nuget\packages\uno.wasm.bootstrap\1.0.0-dev.196\build\Uno.Wasm.Bootstrap.targets(118,5): error : System.Exception: Failed to execute the linker
```

**Comment by jeromelaban** [comment]
If you had used it under any other platform it would have been the same :)

The last issue you're mentioning is an Uno.Wasm.Boostrap issue with the linker, where the Microsoft.CodeAnalysis.CSharp.Workspaces assembly is not part of the referenced assemblies, because there are no code references to it when building the main assembly (all types are internal) and Roslyn loads it via reflection.

I've disabled the linker in #5 until this gets fixed, so you can get the sample running, and the compilation working.
