### ISSUE TITLE
Runtime error using the library

### ISSUE THREAD

**Issue by nologinatgit** [unoplatform/Uno.SQLitePCLRaw.Wasm#8]
I have created a default UNO project and added the Microsoft.EntityFrameworkCore 3.1.5 NuGet package to each of the projects. After that I added the latest prerelease version of this library (v2.0.0-dev.6)

I have the following references in the Wasm project:

![image](https://user-images.githubusercontent.com/4659744/86147672-f5b31a00-baf9-11ea-9b3a-418b44b9a972.png)

I added the following to the `Program.cs` file of the Wasm project:

 `SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_WebAssembly());`

I have the following code in the shared `MainPage.xaml.cs` file:
   ```
  using (context = new MountainContext())
  {
     context.Database.EnsureCreated();
     //mountains = new ObservableRangeCollection<MountainItem>(context.Mountains);
     //await Task.Delay(3000);
     //dataGrid.ItemsSource = mountains;
   }
```

Whenever I start the application in the Kestrel server, I get the following error:

![image](https://user-images.githubusercontent.com/4659744/86148071-72de8f00-bafa-11ea-925e-8b45c665d6e6.png)

What else should I modify?

**Comment by jeromelaban** [comment]
We're in the process of updating to a recent mono build. There were some issues in mono that have been fixed, and the update will be able to move forward.

**Comment by nologinatgit** [comment]
> We're in the process of updating to a recent mono build. There were some issues in mono that have been fixed, and the update will be able to move forward.

Good news. 
Can I ask when you plan to release a production ready library? I see a handful of tools and libraries but most of them are still in a prerelease version. Same applies to the announced Syncfusion components - what are the future plans?

**Comment by francoistanguay** [comment]
@nologinatgit  Whichi Syncfusion controls are you interested in primarily?

**Comment by nologinatgit** [comment]
> @nologinatgit Whichi Syncfusion controls are you interested in primarily?

I intend to use their SfDataGrid component. Unfortunately, it is available in UWP and Xamarin format, no WebAssembly (only in the UnoConf 2019 hint about being released soon).

**Comment by jeromelaban** [comment]
@nologinatgit You can now see an updated sample here: https://github.com/unoplatform/Uno.Samples/tree/master/UI/SQLiteSample

<blockquote><img src="https://avatars1.githubusercontent.com/u/52228309?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/unoplatform/Uno.Samples">unoplatform/Uno.Samples</a></strong></div><div>A collection of code samples for the Uno Platform. Contribute to unoplatform/Uno.Samples development by creating an account on GitHub.</div></blockquote>
